
project_name: duckvault

builds:
  - binary: duckvault
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
release:
  prerelease: auto

universal_binaries:
  - replace: true


